[2024-03-30T01:22:08.464+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:22:08.467+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:22:08.529+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:22:08.532+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:22:08.600+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:19:52.121945+00:00 [queued]>
[2024-03-30T01:22:08.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:19:52.121945+00:00 [queued]>
[2024-03-30T01:22:08.617+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-03-30T01:22:08.638+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_combined> on 2024-03-30 01:19:52.121945+00:00
[2024-03-30T01:22:08.643+0000] {standard_task_runner.py:57} INFO - Started process 5545 to run task
[2024-03-30T01:22:08.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bcra_data_pipeline', 'load_to_redshift_combined', 'manual__2024-03-30T01:19:52.121945+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag_bcra.py', '--cfg-path', '/tmp/tmp_j15g5ow']
[2024-03-30T01:22:08.649+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask load_to_redshift_combined
[2024-03-30T01:22:08.716+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:22:08.725+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:19:52.121945+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:22:08.732+0000] {task_command.py:416} INFO - Running <TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:19:52.121945+00:00 [running]> on host a74e6333f8c5
[2024-03-30T01:22:08.835+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bcra_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift_combined' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T01:19:52.121945+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T01:19:52.121945+00:00'
[2024-03-30T01:22:08.887+0000] {logging_mixin.py:154} INFO - Creating Redshift connection...
[2024-03-30T01:22:08.921+0000] {utils.py:52} INFO - Conectándose a la base de datos...
[2024-03-30T01:22:08.922+0000] {utils.py:59} INFO - Conexión a la base de datos establecida exitosamente
[2024-03-30T01:22:08.923+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_bcra.py", line 253, in load_to_redshift_combined
    with engine.connection() as conn:
AttributeError: 'Engine' object has no attribute 'connection'
[2024-03-30T01:22:08.970+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bcra_data_pipeline, task_id=load_to_redshift_combined, execution_date=20240330T011952, start_date=20240330T012208, end_date=20240330T012208
[2024-03-30T01:22:08.984+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-30T01:22:11.455+0000] {logging_mixin.py:154} INFO - Email sent successfully!
[2024-03-30T01:22:11.654+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task load_to_redshift_combined ('Engine' object has no attribute 'connection'; 5545)
[2024-03-30T01:22:11.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-30T01:22:11.696+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
