[2024-03-29T22:52:41.173+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-29T22:52:41.177+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined'
[2024-03-29T22:52:41.243+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-29T22:52:41.246+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined'
[2024-03-29T22:52:41.320+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined scheduled__2024-03-28T07:00:00+00:00 [queued]>
[2024-03-29T22:52:41.338+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined scheduled__2024-03-28T07:00:00+00:00 [queued]>
[2024-03-29T22:52:41.339+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-29T22:52:41.359+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_combined> on 2024-03-28 07:00:00+00:00
[2024-03-29T22:52:41.367+0000] {standard_task_runner.py:57} INFO - Started process 335 to run task
[2024-03-29T22:52:41.371+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bcra_data_pipeline', 'load_to_redshift_combined', 'scheduled__2024-03-28T07:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_bcra.py', '--cfg-path', '/tmp/tmpzcb1o6rn']
[2024-03-29T22:52:41.375+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask load_to_redshift_combined
[2024-03-29T22:52:41.458+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-29T22:52:41.459+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=scheduled__2024-03-28T07:00:00+00:00/task_id=load_to_redshift_combined'
[2024-03-29T22:52:41.466+0000] {task_command.py:416} INFO - Running <TaskInstance: bcra_data_pipeline.load_to_redshift_combined scheduled__2024-03-28T07:00:00+00:00 [running]> on host 5d7162670411
[2024-03-29T22:52:41.594+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bcra_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift_combined' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T07:00:00+00:00'
[2024-03-29T22:52:41.680+0000] {logging_mixin.py:154} INFO - Creating Redshift connection...
[2024-03-29T22:52:41.709+0000] {utils.py:48} INFO - Conectándose a la base de datos...
[2024-03-29T22:52:41.710+0000] {utils.py:55} INFO - Conexión a la base de datos establecida exitosamente
[2024-03-29T22:52:41.711+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_bcra.py", line 156, in load_to_redshift_combined
    with engine.connection() as conn:
AttributeError: 'Engine' object has no attribute 'connection'
[2024-03-29T22:52:41.771+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bcra_data_pipeline, task_id=load_to_redshift_combined, execution_date=20240328T070000, start_date=20240329T225241, end_date=20240329T225241
[2024-03-29T22:52:41.790+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task load_to_redshift_combined ('Engine' object has no attribute 'connection'; 335)
[2024-03-29T22:52:41.825+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-29T22:52:41.849+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
