[2024-03-30T01:14:28.305+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:14:28.308+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:14:28.367+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:14:28.370+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:14:28.437+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:11:10.523112+00:00 [queued]>
[2024-03-30T01:14:28.451+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:11:10.523112+00:00 [queued]>
[2024-03-30T01:14:28.452+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2024-03-30T01:14:28.474+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_combined> on 2024-03-30 01:11:10.523112+00:00
[2024-03-30T01:14:28.479+0000] {standard_task_runner.py:57} INFO - Started process 5018 to run task
[2024-03-30T01:14:28.482+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bcra_data_pipeline', 'load_to_redshift_combined', 'manual__2024-03-30T01:11:10.523112+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_bcra.py', '--cfg-path', '/tmp/tmpuydpn7rd']
[2024-03-30T01:14:28.486+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask load_to_redshift_combined
[2024-03-30T01:14:28.554+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:14:28.555+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:14:28.558+0000] {task_command.py:416} INFO - Running <TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:11:10.523112+00:00 [running]> on host a74e6333f8c5
[2024-03-30T01:14:28.659+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bcra_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift_combined' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T01:11:10.523112+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T01:11:10.523112+00:00'
[2024-03-30T01:14:28.714+0000] {logging_mixin.py:154} INFO - Creating Redshift connection...
[2024-03-30T01:14:28.725+0000] {utils.py:48} INFO - Conectándose a la base de datos...
[2024-03-30T01:14:28.727+0000] {utils.py:55} INFO - Conexión a la base de datos establecida exitosamente
[2024-03-30T01:14:28.727+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_bcra.py", line 253, in load_to_redshift_combined
    with engine.connection() as conn:
AttributeError: 'Engine' object has no attribute 'connection'
[2024-03-30T01:14:28.750+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bcra_data_pipeline, task_id=load_to_redshift_combined, execution_date=20240330T011110, start_date=20240330T011428, end_date=20240330T011428
[2024-03-30T01:14:28.766+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-30T01:14:31.261+0000] {logging_mixin.py:154} INFO - Email sent successfully!
[2024-03-30T01:14:31.483+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task load_to_redshift_combined ('Engine' object has no attribute 'connection'; 5018)
[2024-03-30T01:14:31.512+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-30T01:14:31.539+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
