[2024-03-30T01:12:24.490+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:12:24.493+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:12:24.553+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:12:24.556+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:12:24.623+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:11:10.523112+00:00 [queued]>
[2024-03-30T01:12:24.638+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:11:10.523112+00:00 [queued]>
[2024-03-30T01:12:24.639+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2024-03-30T01:12:24.659+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_combined> on 2024-03-30 01:11:10.523112+00:00
[2024-03-30T01:12:24.664+0000] {standard_task_runner.py:57} INFO - Started process 4874 to run task
[2024-03-30T01:12:24.666+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bcra_data_pipeline', 'load_to_redshift_combined', 'manual__2024-03-30T01:11:10.523112+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag_bcra.py', '--cfg-path', '/tmp/tmpm_0k3b23']
[2024-03-30T01:12:24.669+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask load_to_redshift_combined
[2024-03-30T01:12:24.745+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T01:12:24.747+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T01:11:10.523112+00:00/task_id=load_to_redshift_combined'
[2024-03-30T01:12:24.752+0000] {task_command.py:416} INFO - Running <TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T01:11:10.523112+00:00 [running]> on host a74e6333f8c5
[2024-03-30T01:12:24.858+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bcra_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift_combined' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T01:11:10.523112+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T01:11:10.523112+00:00'
[2024-03-30T01:12:24.923+0000] {logging_mixin.py:154} INFO - Creating Redshift connection...
[2024-03-30T01:12:24.935+0000] {utils.py:48} INFO - Conectándose a la base de datos...
[2024-03-30T01:12:24.936+0000] {utils.py:55} INFO - Conexión a la base de datos establecida exitosamente
[2024-03-30T01:12:24.937+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_bcra.py", line 253, in load_to_redshift_combined
    with engine.connection() as conn:
AttributeError: 'Engine' object has no attribute 'connection'
[2024-03-30T01:12:24.967+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bcra_data_pipeline, task_id=load_to_redshift_combined, execution_date=20240330T011110, start_date=20240330T011224, end_date=20240330T011224
[2024-03-30T01:12:24.984+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task load_to_redshift_combined ('Engine' object has no attribute 'connection'; 4874)
[2024-03-30T01:12:25.040+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-30T01:12:25.078+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
