[2024-03-30T00:38:37.474+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T00:38:37.477+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined'
[2024-03-30T00:38:37.538+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T00:38:37.541+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined'
[2024-03-30T00:38:37.617+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T00:38:24.501527+00:00 [queued]>
[2024-03-30T00:38:37.632+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T00:38:24.501527+00:00 [queued]>
[2024-03-30T00:38:37.633+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-30T00:38:37.651+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_combined> on 2024-03-30 00:38:24.501527+00:00
[2024-03-30T00:38:37.656+0000] {standard_task_runner.py:57} INFO - Started process 2745 to run task
[2024-03-30T00:38:37.659+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bcra_data_pipeline', 'load_to_redshift_combined', 'manual__2024-03-30T00:38:24.501527+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag_bcra.py', '--cfg-path', '/tmp/tmphpoa5wcw']
[2024-03-30T00:38:37.662+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask load_to_redshift_combined
[2024-03-30T00:38:37.732+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T00:38:37.733+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:38:24.501527+00:00/task_id=load_to_redshift_combined'
[2024-03-30T00:38:37.738+0000] {task_command.py:416} INFO - Running <TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T00:38:24.501527+00:00 [running]> on host a74e6333f8c5
[2024-03-30T00:38:37.850+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bcra_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift_combined' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:38:24.501527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T00:38:24.501527+00:00'
[2024-03-30T00:38:37.906+0000] {logging_mixin.py:154} INFO - Creating Redshift connection...
[2024-03-30T00:38:37.919+0000] {utils.py:48} INFO - Conectándose a la base de datos...
[2024-03-30T00:38:37.920+0000] {utils.py:55} INFO - Conexión a la base de datos establecida exitosamente
[2024-03-30T00:38:37.920+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_bcra.py", line 217, in load_to_redshift_combined
    with engine.connection() as conn:
AttributeError: 'Engine' object has no attribute 'connection'
[2024-03-30T00:38:37.942+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bcra_data_pipeline, task_id=load_to_redshift_combined, execution_date=20240330T003824, start_date=20240330T003837, end_date=20240330T003837
[2024-03-30T00:38:37.959+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task load_to_redshift_combined ('Engine' object has no attribute 'connection'; 2745)
[2024-03-30T00:38:37.993+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-30T00:38:38.014+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
