[2024-03-30T00:01:21.444+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T00:01:21.448+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined'
[2024-03-30T00:01:21.527+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T00:01:21.531+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined'
[2024-03-30T00:01:21.639+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T00:01:06.797051+00:00 [queued]>
[2024-03-30T00:01:21.671+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T00:01:06.797051+00:00 [queued]>
[2024-03-30T00:01:21.672+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-30T00:01:21.725+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_combined> on 2024-03-30 00:01:06.797051+00:00
[2024-03-30T00:01:21.734+0000] {standard_task_runner.py:57} INFO - Started process 397 to run task
[2024-03-30T00:01:21.740+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bcra_data_pipeline', 'load_to_redshift_combined', 'manual__2024-03-30T00:01:06.797051+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_bcra.py', '--cfg-path', '/tmp/tmp8xfs9mih']
[2024-03-30T00:01:21.747+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask load_to_redshift_combined
[2024-03-30T00:01:21.846+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined permission to 509
[2024-03-30T00:01:21.847+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bcra_data_pipeline/run_id=manual__2024-03-30T00:01:06.797051+00:00/task_id=load_to_redshift_combined'
[2024-03-30T00:01:21.851+0000] {task_command.py:416} INFO - Running <TaskInstance: bcra_data_pipeline.load_to_redshift_combined manual__2024-03-30T00:01:06.797051+00:00 [running]> on host a74e6333f8c5
[2024-03-30T00:01:22.048+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bcra_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift_combined' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:01:06.797051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T00:01:06.797051+00:00'
[2024-03-30T00:01:22.118+0000] {logging_mixin.py:154} INFO - Creating Redshift connection...
[2024-03-30T00:01:22.131+0000] {utils.py:48} INFO - Conectándose a la base de datos...
[2024-03-30T00:01:22.133+0000] {utils.py:55} INFO - Conexión a la base de datos establecida exitosamente
[2024-03-30T00:01:22.134+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_bcra.py", line 156, in load_to_redshift_combined
    with engine.connection() as conn:
AttributeError: 'Engine' object has no attribute 'connection'
[2024-03-30T00:01:22.165+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bcra_data_pipeline, task_id=load_to_redshift_combined, execution_date=20240330T000106, start_date=20240330T000121, end_date=20240330T000122
[2024-03-30T00:01:22.186+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task load_to_redshift_combined ('Engine' object has no attribute 'connection'; 397)
[2024-03-30T00:01:22.317+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-30T00:01:22.354+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
